### ISSUE TITLE
[BUG] 분산락 타임아웃 상황에서 트랜잭션 롤백 문제 해결  

### ISSUE THREAD

**Issue by chhs2131** [woowa-techcamp-2024/Team7-ELEVEN#342]
### 🐞 Describe

레디슨락의 LeaseTime을 초과하여 중도 반환하였으나, 어플리케이션 로직 진행 중에는 이를 인지하지 못하고 있게 된다.
트랜잭션 Commit 이후 레디슨락을 unlcok하는 시점에서 이를 발견하고 익셉션이 발생하는 경우, 트랜잭션이 롤백되지 않아 데이터 정합성 문제가 발생한다.

### 문제 그림
<img width="716" alt="image" src="https://github.com/user-attachments/assets/cf1abdd8-317c-49ed-a4ff-edda3390d6c5">

<br/>
<br/>

### 할일 
- 타이머를 통해 락을 관리한다.
- TransactionalWithTimer 추가  
  - 기존 트랜잭셔널에 타임아웃 값이 있다. 이걸 활용해보자! 
  - https://blog.outsider.ne.kr/870
- Sleep줘서 테스트 확인해보기 
  - 테스트 상황 가정: 분산락 lease time을 초과하는 입찰 로직은 정상적으로 실패하고 롤백된다.
    - 한명의 유저가 입찰 로직을 시작
    - Lock 획득
    - 트랜잭션 시작
    - 입찰 작업이 너무 길어져 Lock lease time을 초과함 (즉, 락을 이 시점에서 잃음)
    - 트랜잭션 타임아웃으로 인해 트랜잭션이 종료됨 
    - Lock 반환에 실패하고 예외 발생 (lease time 초과 시점에서 이미 반환됨)

<br/>
<br/>

### 목표 그림
<img width="727" alt="image" src="https://github.com/user-attachments/assets/3960d881-6ff2-4176-a945-10c9dca4d825">

### 📄 Logs

```shell
java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: 75ebcea1-e441-429b-a063-93224ce1c8e2 thread-id: 1
	at org.redisson.RedissonBaseLock.lambda$unlockAsync0$2(RedissonBaseLock.java:309)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:648)
	at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:624)
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:601)
	at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:201)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:530)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:524)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:444)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:218)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:146)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840
```

### 🙋🏻 More

마지막날이야~~~ 힘을내~~~

**Comment by chhs2131** [comment]
Version2 스프링 부트라고 상위에 아스키 아트 추가 ㄱㄱ
